### ISSUE TITLE
Broken pages in recent update

### ISSUE THREAD

**Issue by TotallyAProgrammer** [Unknown-Technology-Solutions/UTS-Site#26]
It seems like several pages broke in the recent commit #24 (as far as I can tell).
They aren't displaying any content. You can see this at [https://testing.unknownts.com/tos.php](https://testing.unknownts.com/tos.php)

**Comment by TotallyAProgrammer** [comment]
@boorishpea

**Comment by boorishpea** [comment]
does includes/templates/tos.tpl exist?

**Comment by TotallyAProgrammer** [comment]
I'll have to take a look in a moment

**Comment by TotallyAProgrammer** [comment]
Resolved. This was caused by certain services not properly starting after a server lost power.
